### PR TITLE
fix: upgrade snyk-docker-plugin to fix nodejs-parser dependency type

### PR DESCRIPTION
**Pull request by adrobuta**
## Pull Request Submission

Please check the boxes once done.

The pull request must:

- **Reviewer Documentation**
    - [ ] follow [CONTRIBUTING](https://github.com/snyk/cli/blob/main/CONTRIBUTING.md) rules
    - [ ] be accompanied by a detailed description of the changes
    - [ ] contain a risk assessment of the change (Low | Medium | High) with regards to breaking existing functionality. A change e.g. of an underlying language plugin can completely break the functionality for that language, but appearing as only a version change in the dependencies.
    - [ ] highlight breaking API if applicable
    - [ ] contain a link to the automatic tests that cover the updated functionality.
    - [ ] contain testing instructions in case that the reviewer wants to manual verify as well, to add to the manual testing done by the author.
    - [ ] link to the link to the PR for the User-facing documentation
- **User facing Documentation**
    - [ ] update any relevant documentation in gitbook by submitting a gitbook PR, and including the PR link here
    - [ ] ensure that the message of the final single commit is descriptive and prefixed with either `feat:` or `fix:` , others might be used in rare occasions as well, if there is no need to document the changes in the release notes. The changes or fixes should be described in detail in the commit message for the changelog & release notes.
- **Testing**
    - [ ] Changes, removals and additions to functionality must be covered by acceptance / integration tests or smoke tests - either already existing ones, or new ones, created by the author of the PR.

## Pull Request Review

All pull requests must undergo a thorough review process before being merged. 
The review process of the code PR should include code review, testing, and any necessary feedback or revisions. 
Pull request reviews of functionality developed in other teams only review the given documentation and test reports. 

Manual testing will not be performed by the reviewing team, and is the responsibility of the author of the PR.

For Node projects: It’s important to make sure changes in `package.json` are also affecting `package-lock.json` correctly.

****************************If a dependency is not necessary, don’t add it.**************************** 

When adding a new package as a dependency, make sure that the change is absolutely necessary. We would like to refrain from adding new dependencies when possible.
Documentation PRs in gitbook are reviewed by Snyk's content team. They will also advise on the best phrasing and structuring if needed.

## Pull Request Approval

Once a pull request has been reviewed and all necessary revisions have been made, it is approved for merging into 
the main codebase. The merging of the code PR is performed by the code owners, the merging of the documentation PR 
by our content writers.

## What does this PR do?

upgrades the version of snyk-docker-plugin 6.12.0-> 6.12.3
there was no change in snyk-docker-plugin@6.12.3 apart of changing the depency type for snyk-resolve-deps from dev to production dependency in this [commit](https://github.com/snyk/snyk-docker-plugin/commit/6decc4566844afd960bb689e9edf37f4de5275c2), this bump is made to avoid possible errors of type:
Cannot find module '`snyk-resolve-deps' from 'node_modules/snyk-docker-plugin/dist/analyzer/applications/node.js'`

### CODE REVIEW

**Comment by PeterSchafer** [comment]
Hi @adrobuta,
Could you please help us and the CLI users better understand what the change means and what it's impact and risk is.
CLI users are often less interested in the bump of a dependency than what the issue exactly is fixed, so that they can understand and decide if a newer version solves a problem they have experienced.
Thanks for your support!

**Comment by adrobuta** [comment]
hi @PeterSchafer, there was no change in snyk-docker-plugin@6.12.3 apart of changing the depency type for snyk-resolve-deps from dev to production dependency, this bump is made to avoid possible errors of type:
`Cannot find module 'snyk-resolve-deps' from 'node_modules/snyk-docker-plugin/dist/analyzer/applications/node.js'`

**Comment by PeterSchafer** [comment]
> hi @PeterSchafer, there was no change in snyk-docker-plugin@6.12.3 apart of changing the depency type for snyk-resolve-deps from dev to production dependency in this [commit](https://github.com/snyk/snyk-docker-plugin/commit/6decc4566844afd960bb689e9edf37f4de5275c2), this bump is made to avoid possible errors of type: `Cannot find module 'snyk-resolve-deps' from 'node_modules/snyk-docker-plugin/dist/analyzer/applications/node.js'`
> 
> Thanks a lot!

Thank you @adrobuta for the additional context! 
To make more sense for external users, we try to focus on describing the what (fix issue xyz) rather than the how (bump plugin version). Applying this here is it correct to say 

> fix (container): Fix issues of type 'Cannot find module ...'

**Comment by adrobuta** [comment]
hi @PeterSchafer , I'm aware of the version change of snyk-nodejs-lockfile-parser from 1.53.0 to 1.57.0, I tested container with the new versions of the dependencies. And I have updated the commit's message to be more suggestive on the what this versions bump tries to solve. thank you!

**Review by PeterSchafer — APPROVED** [review]

**Pull request merged**
