### PR TITLE
fix: add proper colour for displaying critical issues/CVEs 

### PR DESCRIPTION
**Pull request by danlucian**
- [x] Follows [CONTRIBUTING](https://github.com/snyk/snyk/blob/master/.github/CONTRIBUTING.md) rules

#### What does this PR do?

Bump the version of the cpp plugin from 2.13.0 to 2.14.0 (https://github.com/snyk/snyk-cpp-plugin/releases/tag/v2.14.0).

#### Any background context you want to provide?

In the version 2.14.0 of the cpp plugin we added support for displaying the critical vulnerabilities.

#### Screenshots

Screenshot 2021-12-02 at 11 35 10

### CODE REVIEW

**Review by anthogez — COMMENTED** [review]
Nice work here @danlucian! 
Small suggestion:

Rephrase the commit message to highlight the changes applied into `snyk-cpp-plugin`
also add the same github notes/message from the pull request that generated the release v2.14.0 of snyk-cpp-plugin.

By adding it into this pr's commit message. Thanks! 🙏

**Comment by danlucian** [comment]
> Nice work here @danlucian! Small suggestion:
> 
> Rephrase the commit message to highlight the changes applied into `snyk-cpp-plugin` also add the same github notes/message from the pull request that generated the release v2.14.0 of snyk-cpp-plugin.
> 
> By adding it into this pr's commit message. Thanks! 🙏

Hi there, I just did that, thank you! 🙏 
Is there a convention in doing this? I didn't see it mentioned here: https://github.com/snyk/snyk/blob/master/.github/CONTRIBUTING.md (neither in other PRs, I used this as a guideline for example: https://github.com/snyk/snyk/pull/2377)

**Review by Avishagp — APPROVED** [review]

**Comment by anthogez** [comment]
> https://github.com/snyk/snyk/blob/master/.github/CONTRIBUTING.md

This might be outdated, we should definitely update it.
As commits should be the source of truth, not the GitHub notes

**Comment by anthogez** [comment]
> > Nice work here @danlucian! Small suggestion:
> > Rephrase the commit message to highlight the changes applied into `snyk-cpp-plugin` also add the same github notes/message from the pull request that generated the release v2.14.0 of snyk-cpp-plugin.
> > By adding it into this pr's commit message. Thanks! 🙏
> 
> Hi there, I just did that, thank you! 🙏 Is there a convention in doing this? I didn't see it mentioned here: https://github.com/snyk/snyk/blob/master/.github/CONTRIBUTING.md (neither in other PRs, I used this as a guideline for example: #2377)

> https://github.com/snyk/snyk/blob/master/.github/CONTRIBUTING.md

@danlucian this might be outdated, we should definitely update it.
As commits should be the source of truth, not the GitHub notes

**Pull request merged**
