### PR TITLE
chore: upgrade to typescript 4.8

### PR DESCRIPTION
**Pull request by candrews**
- [x] Follows [CONTRIBUTING](https://github.com/snyk/snyk/blob/master/CONTRIBUTING.md) rules

#### What does this PR do?
Upgrade typescript from 3.9.10 to 4.8.3

Includes necessary upgrades to these packages as well: @typescript-eslint/eslint-plugin
@typescript-eslint/parser
eslint
eslint-config-prettier
eslint-plugin-jest
jest
tap
ts-jest
ts-loader
ts-node

#### Where should the reviewer start?
There's no functional change here. The only changes made are the results newly identified issues from the upgraded typescript and eslint.

#### How should this be manually tested?
Run snyk :)

#### Any background context you want to provide?
Using the latest versions of dependencies is a general best practice for a number of reasons.

My primary motivation here is that I want to add a feature to snyk cli (for which I will submit a pull request in the future) that uses a dependency that's written in Typescript 4.8, and Typescript 3.9 (which snyk cli currently uses) cannot compile against it.

### CODE REVIEW

**Comment by candrews** [comment]
@magdziarek could you please take a look? Thank you!

**Review by novalex — DISMISSED** [review]

**Comment by candrews** [comment]
I just rebased this again...

@novalex thank you for the approval!

@teodora-sandu @jonathansantilli @admons @tonidevine1 and anyone else - Is there anything I can do to move this along?

**Comment by PeterSchafer** [comment]
Dear @candrews,
thank you very much for your contribution. We have reviewed your changes and they generally look good. Unfortunately they cause tests to fail.
You should be able to reproduce this by running `npm run test` while some tests might locally fail due to missing dependencies, some failures are related to the changes in the PR itself.
Thanks again!

**Comment by candrews** [comment]
Thanks for this information and for enabling workflows! I'll get right on figuring out and addressing these issues.

**Comment by candrews** [comment]
I've updated this PR with all the tests fixed.

When I run `npm test` now, I get the same result as when I run `npm test` again `master`, which is that these 4 tests fail:
```
Summary of all failing tests
 FAIL  test/jest/unit/lib/ecosystems/resolve-test-facts.spec.ts
  ● resolve and test facts › successfully resolving and testing file-signatures fact for c/c++ projects with new unmanaged service

    getaddrinfo ENOTFOUND api.example.com



  ● resolve and test facts › failed resolving and testing file-signatures since createDepGraph throws exception with new unmanaged service

    getaddrinfo ENOTFOUND api.example.com



  ● resolve and test facts › failed resolving and testing file-signatures since getDepGraph throws exception with new unmanaged service

    getaddrinfo ENOTFOUND api.example.com



  ● resolve and test facts › failed resolving and testing file-signatures since getIssues throws exception with new unmanaged service

    getaddrinfo ENOTFOUND api.example.com
```

Thank you again for taking a look, approving the workflow, and providing feedback. I believe your concerns have now been addressed, so hopefully this is now ready to merge.

**Comment by candrews** [comment]
I updated this branch fixing the error in `test/jest/acceptance/config.spec.ts` that the `test_and_release` workflow discovered (`npm test` didn't report this error, so I didn't know about :shrug:).

**Comment by candrews** [comment]
@PeterSchafer I updated this PR fixing the error in `test/jest/acceptance/config.spec.ts` that the `test_and_release` workflow discovered (`npm test` didn't report this error, so I didn't know about it :shrug:).

**Comment by PeterSchafer** [comment]
@candrews Thanks for the additional changes. I just triggered `test_and_release` again and it continues to fail. First because of a linting issue, second due to other tests still failing. Could you please run `npm run format` before a commit.
The failing tests should be reproducible when running the individual test targets like `npm run test:unit`. I hope this helps.

**Comment by candrews** [comment]
> Could you please run `npm run format` before a commit.

I'm sorry I forgot to do that :(

> The failing tests should be reproducible when running the individual test targets like `npm run test:unit`.

I fixed the "tap" test compilation errors. I get failures in the tests themselves, but I'm hoping that's due to my system's setup and that they pass when run in the workflow environment.

[The node 12 tests is failing](https://circleci.com/gh/snyk/cli/166582?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-checks-link) because Typescript no longer Node 12. Node 12 has been end of life and out of support since 30 Apr 2022 (5 months ago). Therefore I suggest Snyk stop running tests with it; I've added a commit to do so.

I don't know why the 2 windows tests, [v2 / Jest Acceptance Tests (windows/amd64)](https://circleci.com/gh/snyk/cli/166620?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-checks-link) and [Acceptance Tests (snyk-win.exe)](https://circleci.com/gh/snyk/cli/166599?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-checks-link), are failing. The tests don't have any output that indicates what the problem is. If you give me some hints as to what the problem is or how I can reproduce it, I'd be happy to do my best to fix it.

**Comment by candrews** [comment]
In the latest run, I don't understand why the [tap tests](https://app.circleci.com/pipelines/github/snyk/cli/15499/workflows/6428ac3f-bd89-4c43-97b8-a473a2005c57/jobs/166679) failed. Is this something you all are familiar with and can help resolve?

Same for the two Windows tests - I can't reproduce them, and the log output doesn't appear useful:
* https://app.circleci.com/pipelines/github/snyk/cli/15499/workflows/6428ac3f-bd89-4c43-97b8-a473a2005c57/jobs/166702
* https://app.circleci.com/pipelines/github/snyk/cli/15499/workflows/6428ac3f-bd89-4c43-97b8-a473a2005c57/jobs/166716

I'd love to help, and I really want to get this PR merged... please give me a hand in doing so :)

**Comment by PeterSchafer** [comment]
@candrews Thanks a lot for the updates.

The failing tests on windows seem to be related to jest not being able to discover the tests. A quick search shows it seems to be a problem others also have. Maybe there is also a solution somewhere.

For the Tap tests, I haven't been able to look into them. Will do this tomorrow.

**Comment by PeterSchafer** [comment]
@candrews We looked into the failing Tap tests. It seems that an internal mock server can not be launched since it fails to bind the port. Subsequent tests appear to have the same issue. Unfortunately the root cause is not obvious.

**Comment by candrews** [comment]
@PeterSchafer I figured it out and pushed a commit just now to fix it. The tap tests now run on my system - could you please trigger the workflow and ensure they work there?

I looked at the Windows tests... I still don't know what's going on with them, and I don't have access to a Windows system on which to reproduce the tests. Do you have any insights on them?

**Comment by candrews** [comment]
I found (and fixed) more race conditions in the tap tests. Can you please run the workflow so can I see if there's anything else wrong?

I continue to not know why the Windows tests faill; I am eager to get whatever information you can share about them.

**Comment by candrews** [comment]
> **code/snyk (Snyk Internal (Org)) ** — 9 new Code Analysis issues found [Details](https://app.snyk.io/org/snyk-internal-org/project/01792408-a646-43a2-a293-7ee71ed79bea/pr-check/211ac2d5-63a5-4727-a5df-f2bc798d6d4e)
> image

I have no idea what this means. And the link goes to an access denied page.

**Comment by candrews** [comment]
I broke this PR up into a few smaller ones that are easier to review in hope of making at least some progress :crossed_fingers:

**Comment by ipapast** [comment]
is this PR still relevant @candrews? or can we close it?

**Comment by candrews** [comment]
It's still relevant. Snyk's typescript dependency is still out of date and per Snyk's own documentation, having out of date dependencies is problematic for maintainbility as well as security.

**Comment by ipapast** [comment]
> It's still relevant. Snyk's typescript dependency is still out of date and per Snyk's own documentation, having out of date dependencies is problematic for maintainbility as well as security.

okay then, I thought this would be done in more, smaller PRs from the comment here https://github.com/snyk/cli/pull/3875#issuecomment-1281388992

**Comment by ipapast** [comment]
> I'd love to get this done in whatever works for Snyk - big PR or small PRs, whatever we can actually do to make progress would be great from my perspective.
> 
> If Snyk wants to do smaller PRs, can the workflows please be run for them, and then we can merge them? #4147 might be a nice starting point.

no problem by me, I was only going through the pull request reviews pending, and noticed the comment I mentioned. feel free to work in any way you prefer :)

**Comment by thisislawatts** [comment]
This upgrade has now been implemented as part of https://github.com/snyk/cli/pull/5046

**Pull request closed without merging**
