### PR TITLE
fix: ./iac-data/ location

### PR DESCRIPTION
**Pull request by YairZ101**
- [x] Follows [CONTRIBUTING](https://github.com/snyk/snyk/blob/master/CONTRIBUTING.md) rules

#### What does this PR do?
Following a [feedback](https://snyk.slack.com/archives/CEPPB1XNE/p1675794455260329) from @lirantal, we've decided to move the location of the `iac-data` folder from the cwd to the Snyk CLI cache directory.

In addition to that, this PR creates a sub-dir in `iac-data` with a random name to allow the IDE to run several scans concurrently without any problem. 

#### How should this be manually tested?
run IaC commands and check that they are still running and working as expected.

### CODE REVIEW

**Review by bastiandoetsch — DISMISSED** [review]

**Comment by YairZ101** [comment]
@ofekatr you have a little bit more context about how custom rules are using the `iac-data` folder(if they even use it, I'm not sure), do you know if this change will affect them in any way?

**Comment by ofekatr** [comment]
>  @ofekatr you have a little bit more context about how custom rules are using the iac-data folder(if they even use it, I'm not sure), do you know if this change will affect them in any way?

@YairZ101 we currently use this directory when pulling custom rule bundles from the customer's registered OCI registry
https://github.com/snyk/cli/blob/8dff90b85ac9da992654f627111929bb84e675a2/src/cli/commands/test/iac/local-execution/rules/oci-pull.ts#L64-L67

**Comment by YairZ101** [comment]
> > @ofekatr you have a little bit more context about how custom rules are using the iac-data folder(if they even use it, I'm not sure), do you know if this change will affect them in any way?
> 
> @YairZ101 we currently use this directory when pulling custom rule bundles from the customer's registered OCI registry
> 
> https://github.com/snyk/cli/blob/8dff90b85ac9da992654f627111929bb84e675a2/src/cli/commands/test/iac/local-execution/rules/oci-pull.ts#L64-L67

so does it mean that the custom rules are getting repulled for each scan? if this is the case then if I understand it correctly this change wouldn't affect them.

**Comment by ofekatr** [comment]
> so does it mean that the custom rules are getting repulled for each scan? if this is the case then if I understand it correctly this change wouldn't affect them.

@YairZ101 This flow downloads the custom rules in every execution and ensures the `iac-data` directory exists before downloading. It assumes the IaC data directory path to be in the `LOCAL_POLICY_ENGINE_DIR` env variable. 
IIUC, this PR attempts to avoid the creation of this directory in the CWD. 
If that's the case, we may need to make additional changes here as well.

**Comment by ofekatr** [comment]
I see now that the exported value for `LOCAL_POLICY_ENGINE_DIR` is updated in this PR and that we use the same value for custom rules. So this should work, and no additional changes are needed
https://github.com/snyk/cli/blob/5168df306f7f7709cde8208020e35ead2a0c5a3b/src/cli/commands/test/iac/local-execution/local-cache.ts#L20

**Review by ofekatr — DISMISSED** [review]

**Review by ofekatr — APPROVED** [review]

**Pull request merged**
