### PR TITLE
fix: [OSM-998] Scanning of .NET projects with the `--dotnet-runtime-resolution` flag now uses existing NuGet package cache if available

### PR DESCRIPTION
**Pull request by dotkas**
## Pull Request Submission

Please check the boxes once done.

The pull request must:

- **Reviewer Documentation**
    - [x] follow [CONTRIBUTING](https://github.com/snyk/cli/blob/master/CONTRIBUTING.md) rules
    - [x] be accompanied by a detailed description of the changes
    - [x] contain a risk assessment of the change (Low | Medium | High) with regards to breaking existing functionality. A change e.g. of an underlying language plugin can completely break the functionality for that language, but appearing as only a version change in the dependencies.
    - [ ] highlight breaking API if applicable
    - [x] contain a link to the automatic tests that cover the updated functionality.
    - [x] contain testing instructions in case that the reviewer wants to manual verify as well, to add to the manual testing done by the author.
    - [ ] link to the link to the PR for the User-facing documentation
- **User facing Documentation**
    - [ ] update any relevant documentation in gitbook by submitting a gitbook PR, and including the PR link here
    - [x] ensure that the message of the final single commit is descriptive and prefixed with either `feat:` or `fix:` , others might be used in rare occasions as well, if there is no need to document the changes in the release notes. The changes or fixes should be described in detail in the commit message for the changelog & release notes.
- **Testing**
    - [x] Changes, removals and additions to functionality must be covered by acceptance / integration tests or smoke tests - either already existing ones, or new ones, created by the author of the PR.

## Pull Request Review

All pull requests must undergo a thorough review process before being merged. 
The review process of the code PR should include code review, testing, and any necessary feedback or revisions. 
Pull request reviews of functionality developed in other teams only review the given documentation and test reports. 

Manual testing will not be performed by the reviewing team, and is the responsibility of the author of the PR.

For Node projects: It’s important to make sure changes in `package.json` are also affecting `package-lock.json` correctly.

****************************If a dependency is not necessary, don’t add it.**************************** 

When adding a new package as a dependency, make sure that the change is absolutely necessary. We would like to refrain from adding new dependencies when possible.
Documentation PRs in gitbook are reviewed by Snyk's content team. They will also advise on the best phrasing and structuring if needed.

## Pull Request Approval

Once a pull request has been reviewed and all necessary revisions have been made, it is approved for merging into 
the main codebase. The merging of the code PR is performed by the code owners, the merging of the documentation PR 
by our content writers.

## What does this PR do?

Bumps the version of `snyk-nuget-plugin` one patch version.

Risk assessment: Low, just performance fixes.

## Where should the reviewer start?

Just `packages.json`.

## How should this be manually tested?

`snyk test --dotnet-runtime-resolution` on any given .NET project of newer origin.

## Any background context you want to provide?

This is a small performance update, see https://github.com/snyk/snyk-nuget-plugin/pull/202 - it drops a `--no-cache` flag and a way of determining output paths as per new Microsoft recommendations. Noting big, and is already covered by quite an amount of acceptance tests: https://github.com/snyk/cli/blob/6fc1d10eb0528ac42f6c6af9c374961ee0d2bd99/test/jest/acceptance/snyk-test/basic-test-all-languages.spec.ts#L186-L300.

So if anything, it should speed up those a bit.

## What are the relevant tickets?

https://snyksec.atlassian.net/browse/OSM-998

## Screenshots

N/A

## Additional questions

N/A

### CODE REVIEW

**Comment by j-luong** [comment]
Issue: @dotkas  Please ensure that the PR title and the final message are more descriptive, see
> ensure that the message of the final single commit is descriptive ...

The current message "[OSM-998] Bumping snyk-nuget-plugin", which will appear in the release notes doesn't give any indication what has changed in the release. Please rephrase the PR title and thereby the squash commit message to explain the change in one sentence from a user perspective. The text will eventually end up here https://github.com/snyk/cli/releases

**Comment by dotkas** [comment]
@j-luong Roger that.

**Comment by dotkas** [comment]
@j-luong something like this?

**Review by j-luong — APPROVED** [review]

**Comment by cmars** [comment]
Looking at https://github.com/snyk/snyk-nuget-plugin/compare/v2.4.0...v2.4.1

I don't see any significant change in compatibility.

I do wonder about how different .NET install versions would react to the change in args passed to `dotnet` though.

**Pull request merged**
