### PR TITLE
SAST - handle 500 errors in case of API failure

### PR DESCRIPTION
**Pull request by metju90**

### CODE REVIEW

**Comment by neonnoon** [comment]
@metju90 , why not open a draft then?

**Comment by metju90** [comment]
> @metju90 , why not open a draft then?

I forgot the existence of drafts!

**Comment by pkey** [comment]
not reviewing. You're welcome :D

**Comment by pkey** [comment]
@metju90 what's up with this one? Can you move it to `draft`, if not relevant yet?

**Comment by metju90** [comment]
@pkey thanks for reminding me about this.

I've converted this to a proper PR. Can you have a look?

**Review by pkey — APPROVED** [review]
Looks ok, I would add a test as well.

**Comment by neonnoon** [comment]
@metju90 is this still needed?

**Comment by metju90** [comment]
> @metju90 is this still needed?

@neonnoon  Yes, but it will take ~1hr to manually reconfirm this PR is still valid

**Comment by metju90** [comment]
I revisited this PR and came to the conclusion that this is no longer valid. If [this](https://github.com/snyk/cli/blob/f6668bdfc428cc42bac5fb523dbc0defc2f04d5c/src/lib/plugins/sast/checks.ts#L15) API call had to throw 500, the initial call to the same server authenticate users most probably would throw 500 too, rendering the changes in this PR useless.

**Pull request closed without merging**
