### PR TITLE
chore: Add experimental test analytics [CFG-2157]

### PR DESCRIPTION
**Pull request by ofekatr**
- [X] Follows [CONTRIBUTING](https://github.com/snyk/snyk/blob/master/CONTRIBUTING.md) rules

#### What does this PR do?

- Computes analytics for the experimental test flow.
- Prints the analytics to the debug logs.
- **DOES NOT** send the analytics.

#### Where should the reviewer start?

```
src/lib/iac/test/v2/analytics
```

#### How should this be manually tested?

- Run `snyk iac test --experimental -d`
- Ensure the printed analytics are the expected ones.

#### Any background context you want to provide?

- The current implementation is discussed in [this Notion page](https://www.notion.so/snyk/Analytics-545ce0ef48e8459a94a8afa5b382b635). The page also describes the analytics that should be computed by the experimental flow, and some ideas for more analytics information that could be useful in the future.

- Because the analytics information that we are going to compute cannot be sent over the network yet, it will be sufficient to print them to a debug logger for the time being. The information we compute must not be shared with the analytics module in the CLI.

- This feature must be implemented in snyk and not in snyk-iac-test, because when we will eventually send the analytics over the network, we must use the analytics package as implemented in the CLI.

<details>
    <summary>IaC analytics example</summary>

  ```json
{
    "iac-type": {
        "armconfig": {
            "count": 1,
            "resource-count": 3
        },
        "cloudformationconfig": {
            "count": 2,
            "resource-count": 13
        },
        "terraformconfig": {
            "count": 10,
            "resource-count": 26,
            "low": 27,
            "high": 22,
            "medium": 10
        },
        "k8sconfig": {
            "count": 4,
            "resource-count": 5
        }
    },
    "packageManager": [
        "armconfig",
        "cloudformationconfig",
        "terraformconfig",
        "k8sconfig"
    ],
    "iac-issues-count": 59,
    "iac-ignored-issues-count": 0,
    "iac-files-count": 17,
    "iac-resources-count": 47,
    "iac-test-binary-version": "0.31.3"
}
  ```
</details>

#### What are the relevant tickets?

- [CFG-2157](https://snyksec.atlassian.net/browse/CFG-2157)

### CODE REVIEW

**Comment by ipapast** [comment]
looks good on my local run and the numbers add up.
image

I assume that the `iac-rules-bundle-version` will be added later. What about this comment/suggestion [here](https://www.notion.so/Analytics-545ce0ef48e8459a94a8afa5b382b635?d=c46c2a905d53453e8791cf19d96dd964#c5d8865c33db4b5389fa02193feede3e)? do we want to add the errors here too?

**Review by ipapast — APPROVED** [review]
looks good on my local run and the numbers add up.
image

I assume that the `iac-rules-bundle-version` will be added later as per comment and we didn't want to default it to empty string, etc. 

What about this comment/suggestion [here](https://www.notion.so/Analytics-545ce0ef48e8459a94a8afa5b382b635?d=c46c2a905d53453e8791cf19d96dd964#c5d8865c33db4b5389fa02193feede3e)? do we want to add the errors here too?

**Comment by ofekatr** [comment]
> What about this comment/suggestion [here](https://www.notion.so/Analytics-545ce0ef48e8459a94a8afa5b382b635?d=c46c2a905d53453e8791cf19d96dd964#c5d8865c33db4b5389fa02193feede3e)? do we want to add the errors here too?

@ipapast I've just added an `iac-error-codes` property to address it, I think it captures what the comment suggested, but please share your feedback too.

**Comment by ipapast** [comment]
> > What about this comment/suggestion [here](https://www.notion.so/Analytics-545ce0ef48e8459a94a8afa5b382b635?d=c46c2a905d53453e8791cf19d96dd964#c5d8865c33db4b5389fa02193feede3e)? do we want to add the errors here too?
> 
> @ipapast I've just added an `iac-error-codes` property to address it, I think it captures what the comment suggested, but please share your feedback too.

I think it's very useful, let's keep it

**Pull request merged**
