### PR TITLE
chore: add workflow to sync Snyk CLI GitBook doc to the CLI repo README

### PR DESCRIPTION
**Pull request by mikeromard**
## Pull Request Submission

Please check the boxes once done.

The pull request must:

- **Reviewer Documentation**
    - [ ] follow [CONTRIBUTING](https://github.com/snyk/cli/blob/master/CONTRIBUTING.md) rules
    - [ ] be accompanied by a detailed description of the changes
    - [ ] contain a risk assessment of the change (Low | Medium | High) with regards to breaking existing functionality. A change e.g. of an underlying language plugin can completely break the functionality for that language, but appearing as only a version change in the dependencies.
    - [ ] highlight breaking API if applicable
    - [ ] contain a link to the automatic tests that cover the updated functionality.
    - [ ] contain testing instructions in case that the reviewer wants to manual verify as well, to add to the manual testing done by the author.
    - [ ] link to the link to the PR for the User-facing documentation
- **User facing Documentation**
    - [ ] update any relevant documentation in gitbook by submitting a gitbook PR, and including the PR link here
    - [ ] ensure that the message of the final single commit is descriptive and prefixed with either `feat:` or `fix:` , others might be used in rare occasions as well, if there is no need to document the changes in the release notes. The changes or fixes should be described in detail in the commit message for the changelog & release notes.
- **Testing**
    - [ ] Changes, removals and additions to functionality must be covered by acceptance / integration tests or smoke tests - either already existing ones, or new ones, created by the author of the PR.

## Pull Request Review

All pull requests must undergo a thorough review process before being merged. 
The review process of the code PR should include code review, testing, and any necessary feedback or revisions. 
Pull request reviews of functionality developed in other teams only review the given documentation and test reports. 

Manual testing will not be performed by the reviewing team, and is the responsibility of the author of the PR.

For Node projects: It’s important to make sure changes in `package.json` are also affecting `package-lock.json` correctly.

****************************If a dependency is not necessary, don’t add it.**************************** 

When adding a new package as a dependency, make sure that the change is absolutely necessary. We would like to refrain from adding new dependencies when possible.
Documentation PRs in gitbook are reviewed by Snyk's content team. They will also advise on the best phrasing and structuring if needed.

## Pull Request Approval

Once a pull request has been reviewed and all necessary revisions have been made, it is approved for merging into 
the main codebase. The merging of the code PR is performed by the code owners, the merging of the documentation PR 
by our content writers.

## What does this PR do?

This PR introduces a GitHub Actions workflow to automatically synchronize content from the Snyk CLI's GitBook documentation to the CLI repository's README. Additionally, the README.md has been manually updated to match the content of the GitBook documentation.

## Where should the reviewer start?

The primary addition is the GitHub Actions workflow file in .github/workflows/. This file contains the script that handles the synchronization process. Reviewers should also note the changes made directly to README.md.

## How should this be manually tested?

1. Trigger the GitHub Action manually or wait for the scheduled run time.
2. Check the README.md in the destination branch (docs/automatic-gitbook-update) to see if it has been updated with content from the GitBook documentation.

## Any background context you want to provide?

The goal of this synchronization is to ensure that the README in the CLI repository is always up-to-date with the latest documentation available on GitBook, reducing redundancy and ensuring accuracy.

This work was mostly done by Noah Grant in this PR https://github.com/snyk/cli/pull/4801 from his fork. I added a bit to his synchronize-readme.yml file to replace relative paths to GitBook images to absolute paths.

## What are the relevant tickets?

N/A

## Screenshots

N/A

### CODE REVIEW

**Comment by thisislawatts** [comment]
@mikeromard this looks like a duplicate of [the existing workflow](https://github.com/snyk/cli/blob/master/.github/workflows/sync-cli-help-to-user-docs.yml). Am I missing something?

**Comment by mikeromard** [comment]
@thisislawatts that existing workflow is for syncing the CLI help docs (https://docs.snyk.io/snyk-cli/commands) to https://github.com/snyk/cli/tree/master/help/cli-commands. This one is to sync _Getting started with the Snyk CLI_ (https://docs.snyk.io/snyk-cli/getting-started-with-the-snyk-cli) to the CLI repo's README file (https://github.com/snyk/cli/blob/master/README.md).

**Comment by thisislawatts** [comment]
Ah, well I clearly missed the important detail, my apologies. What research have we done that demonstrates the audience for the GitHub README.md file matches exactly with the intended reader of the linked documentation? My own perspective is that the GitHub readme is an entry point to the software project AND the product.

**Comment by mikeromard** [comment]
No need to apologize :)

This is work that started before I joined Snyk. I'll look into what research was done around it and get back to you with that.

**Review by thisislawatts — APPROVED** [review]

**Pull request merged**
