### PR TITLE
chore: check PRs for missing and unused deps

### PR DESCRIPTION
**Pull request by ghost**
Related to #1942

We don't want to be in a position where we have missing or unused deps. All direct deps should be included in our package.json (to avoid transitive dependence) and any unused deps should be removed.

<details>
<summary>Example</summary>

```
--------------------------------

Checking /home/runner/work/snyk/snyk

  1 Unused Production Dependencies
    - snyk-tree

  6 Unused Development Dependencies
    - @types/agent-base
    - @types/diff
    - @types/jest
    - lodash.countby
    - lodash.every
    - tape

  5 Missing Dependencies
    - danger
      > /home/runner/work/snyk/snyk/dangerfile.js
    - ajv
      > /home/runner/work/snyk/snyk/test/acceptance/cli-test/cli-test.generic.spec.ts
    - lodash.merge
      > /home/runner/work/snyk/snyk/src/lib/protect/index.js
      > /home/runner/work/snyk/snyk/src/lib/module-info/index.ts
    - glob
      > /home/runner/work/snyk/snyk/src/lib/protect/patch.js
      > /home/runner/work/snyk/snyk/scripts/check-dependencies.ts
    - js-yaml
      > /home/runner/work/snyk/snyk/src/lib/iac/iac-parser.ts
      > /home/runner/work/snyk/snyk/src/cli/commands/test/iac-local-execution/file-parser.ts

--------------------------------

Checking /home/runner/work/snyk/snyk/packages/snyk-fix

  3 Unused Production Dependencies
    - bottleneck
    - child_process
    - lodash.orderby

  1 Unused Development Dependencies
    - @types/jest

--------------------------------

Checking /home/runner/work/snyk/snyk/packages/snyk-protect

  2 Missing Dependencies
    - fs-extra
      > /home/runner/work/snyk/snyk/packages/snyk-protect/test/util/createProject.ts
      > /home/runner/work/snyk/snyk/packages/snyk-protect/test/util/getPatchedLodash.ts
      > /home/runner/work/snyk/snyk/packages/snyk-protect/test/util/useLocalPackage.ts
      > /home/runner/work/snyk/snyk/packages/snyk-protect/test/unit/fetch-patches.spec.ts
    - cross-spawn
      > /home/runner/work/snyk/snyk/packages/snyk-protect/test/util/runCommand.ts

--------------------------------

Problems found. See output above.
```

</details>

For this PR to pass, the current dependency issues need to be resolved. See the output logs here: https://github.com/snyk/snyk/runs/2640402673

- [x] #1942 
- [x] #1936 
- [x] Unused deps in @snyk/fix
- [x] Missing deps in @snyk/protect

### CODE REVIEW

**Review by maxjeffos — APPROVED** [review]

**Review by gitphill — APPROVED** [review]
❤️

**Comment by ipapast** [comment]
hey @jahed-snyk #1936 is now merged

**Review by maxjeffos — APPROVED** [review]

**Review by JamesPatrickGill — APPROVED** [review]
Looks sound to me 😄

**Review by lili2311 — APPROVED** [review]
✔️ for @snyk/fix changes. Thanks!

**Pull request merged**
