### PR TITLE
[LINK-699] feat: sbom maven & gradle extra args support

### PR DESCRIPTION
**Pull request by danlucian**
- [x] Follows [CONTRIBUTING](https://github.com/snyk/snyk/blob/master/CONTRIBUTING.md) rules

#### What does this PR do?

Add support for the following args for the `snyk sbom` command:

**maven**:

- `--maven-aggregate-project`
- `--scan-unmanaged --file=<JAR_FILE_NAME> `
- `--scan-all-unmanaged`

**gradle**:

- `--sub-project=<NAME>, --gradle-sub-project=<NAME>`
- `--all-sub-projects`
- `--configuration-matching=<CONFIGURATION_REGEX>`
- `--configuration-attributes=<ATTRIBUTE>[,<ATTRIBUTE>]...`
- `--init-script=<FILE>`

### CODE REVIEW

**Comment by bastiandoetsch** [comment]
Hey Dan, would you mind adding Acceptance Tests for the additional parameters, so that the integration into the CLI is tested sufficiently?

**Review by bastiandoetsch — APPROVED** [review]
Nice!

**Review by topaztee — APPROVED** [review]

**Comment by topaztee** [comment]
Why not also update https://github.com/snyk/cli/blob/ff6575ec180d59528f51e98148fe151471b161c5/help/cli-commands/sbom.md
so users will be able to see the newly available commands through `snyk sbom --help`

**Comment by topaztee** [comment]
> Why not also update https://github.com/snyk/cli/blob/ff6575ec180d59528f51e98148fe151471b161c5/help/cli-commands/sbom.md so users will be able to see the newly available commands through `snyk sbom --help`

scratch that, @danlucian informed me its done via gitbooks

**Pull request merged**
