### PR TITLE
fix :[SUP-2193] Fix `v2` .net parsing not honoring missing `rid`s.

### PR DESCRIPTION
**Pull request by dotkas**
Bump of https://github.com/snyk/snyk-nuget-plugin/pull/192

### CODE REVIEW

**Review by JamesPatrickGill — APPROVED** [review]

**Comment by bastiandoetsch** [comment]
This needs a rebase/merge :). Also, let's not release it this week - happy to review, though.

**Review by bastiandoetsch — CHANGES_REQUESTED** [review]
Request changes: please update against main :). Voting against a release on a Friday :)

**Comment by dotkas** [comment]
> Request changes: please update against main :). Voting against a release on a Friday :)

Yeah, it's no problem. Also it disclosed a bug, so let's revisit next week.

**Review by bastiandoetsch — APPROVED** [review]

**Review by bastiandoetsch — COMMENTED** [review]
unblocked

**Pull request merged**
