### PR TITLE
feat: Add ARM Support for 'iac test'

### PR DESCRIPTION
**Pull request by YairZ101**
- [x] Follows [CONTRIBUTING](https://github.com/snyk/snyk/blob/master/.github/CONTRIBUTING.md) rules

#### What does this PR do?
Azure Resource Manager (ARM) is the native platform for infrastructure as code (IaC) in Azure. It enables you to centralize the management, deployment, and security of Azure resources.
This PR adds the ability to test ARM files by using the `snyk iac test` command.

#### How should this be manually tested?
By testing the ARM file located at `test/fixtures/iac/arm/rule_test.json`.

#### What are the relevant tickets?
[CFG-1141](https://snyksec.atlassian.net/jira/software/c/projects/CFG/boards/301?modal=detail&selectedIssue=CFG-1141)

### CODE REVIEW

**Review by aron — CHANGES_REQUESTED** [review]
This is looking fantastic @YairZ101. I'll build and run locally a little later today before approving but a couple of things in the meantime:

1. Theres a comment about the new policy type that I think can be refactored.
2. Move the smoke tests to acceptance tests.
3. Find where we count the number of test files in the analytics and include arm counts (the team can help find the specific file here).

**Review by aron — CHANGES_REQUESTED** [review]
Ran this locally, it's working great. I spotted a couple of bugs with the `--json` output due to the missing `type` value and the calcluation of the path. It would be great to have these fixed up. And then I think we're good to go 🎉

**Review by aron — COMMENTED** [review]
Great progress so far, it looks like the DocId is the only part left to change, I had a look locally and it looks like just not returning the `docId` or returning `undefined` will sort out the path.

**Review by aron — APPROVED** [review]
🎉  Amazing work, thank you for sticking with me here and working through the feedback. This looks to be in great shape, well done.

**Review by ghost — APPROVED** [review]

**Pull request merged**
