### PR TITLE
fix: adjust `snyk test` output when run with --all-projects

### PR DESCRIPTION
**Pull request by gavinsharp**
- [x] Follows [CONTRIBUTING](https://github.com/snyk/snyk/blob/master/CONTRIBUTING.md) rules

#### What does this PR do?
Fixes https://github.com/snyk/cli/issues/1339.

Adjusts the `test` formatter `displayResults` function to print `displayTargetFile` instead of `options.path` when run with `allProjects`, since that is more useful.

#### How should this be manually tested?
I modified this code locally and ran:
```
snyk --legacy-cli test --all-projects
```
in a monorepo.

#### What are the relevant tickets?
https://github.com/snyk/cli/issues/1339

##### Before
```
Testing /Users/gavin/dev/test-monorepo...

Organization:      cloud-6y6
Package manager:   npm
Target file:       package.json
Project name:      test-monorepo
Open source:       no
Project path:      /Users/gavin/dev/test-monorepo
Licenses:          enabled

✔ Tested /Users/gavin/dev/test-monorepo for known issues, no vulnerable paths found.

Next steps:
- Run `snyk monitor` to be notified about new related vulnerabilities.
- Run `snyk test` as part of your CI/test.

-------------------------------------------------------

Testing /Users/gavin/dev/test-monorepo...

Organization:      cloud-6y6
Package manager:   npm
Target file:       packages/one/package.json
Project name:      one
Open source:       no
Project path:      /Users/gavin/dev/test-monorepo
Licenses:          enabled

✔ Tested /Users/gavin/dev/test-monorepo for known issues, no vulnerable paths found.

Next steps:
- Run `snyk monitor` to be notified about new related vulnerabilities.
- Run `snyk test` as part of your CI/test.

-------------------------------------------------------

Testing /Users/gavin/dev/test-monorepo...

Organization:      cloud-6y6
Package manager:   npm
Target file:       packages/two/package.json
Project name:      two
Open source:       no
Project path:      /Users/gavin/dev/test-monorepo
Licenses:          enabled

✔ Tested /Users/gavin/dev/test-monorepo for known issues, no vulnerable paths found.

Next steps:
- Run `snyk monitor` to be notified about new related vulnerabilities.
- Run `snyk test` as part of your CI/test.


Tested 3 projects, no vulnerable paths were found.
```

##### After
```
Testing package.json...

Organization:      cloud-6y6
Package manager:   npm
Target file:       package.json
Project name:      test-monorepo
Open source:       no
Project path:      /Users/gavin/dev/test-monorepo
Licenses:          enabled

✔ Tested package.json for known issues, no vulnerable paths found.

Next steps:
- Run `snyk monitor` to be notified about new related vulnerabilities.
- Run `snyk test` as part of your CI/test.

-------------------------------------------------------

Testing packages/one/package.json...

Organization:      cloud-6y6
Package manager:   npm
Target file:       packages/one/package.json
Project name:      one
Open source:       no
Project path:      /Users/gavin/dev/test-monorepo
Licenses:          enabled

✔ Tested packages/one/package.json for known issues, no vulnerable paths found.

Next steps:
- Run `snyk monitor` to be notified about new related vulnerabilities.
- Run `snyk test` as part of your CI/test.

-------------------------------------------------------

Testing packages/two/package.json...

Organization:      cloud-6y6
Package manager:   npm
Target file:       packages/two/package.json
Project name:      two
Open source:       no
Project path:      /Users/gavin/dev/test-monorepo
Licenses:          enabled

✔ Tested packages/two/package.json for known issues, no vulnerable paths found.

Next steps:
- Run `snyk monitor` to be notified about new related vulnerabilities.
- Run `snyk test` as part of your CI/test.


Tested 3 projects, no vulnerable paths were found.
```

### CODE REVIEW

**Review by bastiandoetsch — APPROVED** [review]
LGTM

**Comment by bastiandoetsch** [comment]
Could you maybe also add a diff of the output when using `--json`?

**Comment by bastiandoetsch** [comment]
> LGTM - we have no tests handling stuff like this?

Once we run the test_and_release workflow, we'll see which acceptance tests fail ;)

**Comment by gavinsharp** [comment]
> > LGTM - we have no tests handling stuff like this?
> 
> Once we run the test_and_release workflow, we'll see which acceptance tests fail ;)

Indeed, I had a really hard time running tests locally due to a bunch of issues fetching mock data etc., so I was hoping CI could do it for me 😄

Happy to adjust tests if someone can approve running them on this PR.

**Comment by gavinsharp** [comment]
> Could you maybe also add a diff of the output when using `--json`?

Just checked, and the diff for JSON output with these changes is empty.

**Comment by dotkas** [comment]
@gavinsharp I'd do it, but I would prefer @bastiandoetsch doing it as I am not a member of hammerhead.

**Pull request closed without merging**
